server:
  port: 8090
spring:
  application:
    name: "Applications-Service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
logging:
  level:
    pe.com.ask: trace
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-doc
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
routes:
  path:
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "loan_application_pragma"
    schema: "public"
    username: "theask"
    password: "elAllan!!12345"