package pe.com.ask.consumer.utils.token;

public final class Token {
    private Token(){}

    public static final String BEARER_TOKEN = "Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJiZTYxZmUxNy01OWNmLTQ5MTEtOGVlNy1lMDQyMzdlZWQ2M2UiLCJpYXQiOjE3NTc1NTc3MjIsImV4cCI6MTc1NzY0NDEyMiwidXNlcklkIjoiYmU2MWZlMTctNTljZi00OTExLThlZTctZTA0MjM3ZWVkNjNlIiwicm9sZSI6IkFETUlOIiwidXNlckRuaSI6IjczMTIyMjE5In0.GFtg5mEAZEdD9U6yeidVyTBuymGqVc8CQMxe9NwqZak7K4E_YsXagJwXpkWczAt0eZTGSu_Dld3c_WLzVN83aErfhP9cltvYv_x8_8Z7BBSLGZ9-KA4MgF4mssQ0YiZbyNVwIWwpc9yxY0C8fqb9Pty96ucg8V5dppc5YZP3cJDwnzas4fifvEPzCxiiFRAeLhi_-yxphaDfSVy6LSwHPiTp0h96zWkYGd9_4TXQ6-pcmLSk0nXO-SYMf5uMAw0A5FywG1YREN_vEN-El7jukOYKBH6HjtnIDaX5JVRSYeCCKitcDayKglAdhnSF5HVGOAFQjbgYfZwtK0iGChWm6w";
}